### ISSUE TITLE
Why default doesn't work as expected?

### ISSUE THREAD

**Issue by Fazendaaa** [aug-riedinger/i18n-node-yaml#2]
Right now I've only two locales support, en and pt, being en the default. When any other option is passed, the api().t() call returns "undefined"; isn't supposed to return the default option?

**Comment by augnustin** [comment]
Hi,

Please send over your yaml file, along with what you call *any other option*, if you want me to help.

Best

**Comment by Fazendaaa** [comment]
@augnustin, it was my bad, sorry. What I've been doing is calling the api("language").t() and works fine, but when language isn't supported it fails. Changing to api().t("maskName", {}, "language") works as expected, even when the language isn't supported it falls back to default language.
