### ISSUE TITLE
the setLocale method is not accessible

### ISSUE THREAD

**Issue by drackp2m** [aug-riedinger/i18n-node-yaml#3]
Should I change the language by manually modifying the cookie?

**Comment by augnustin** [comment]
Nope, but I agree the doc is unclear on this.

There are 3 successive ways to detect locale in the middleware.

1. Query parameter: If you query `/whatever?lang=en`, then the locale is overriden, and the cookie updated.
2. If absent, the middleware looks for the cookie value
3. If absent, it goes for the best match from the `accept-language` header. 

The `?lang=` can be changed within the options by updating the `queryParameters` (note that this is an array, multiple values can be accepted).

Hope it helps, good luck

**Comment by augnustin** [comment]
I updated the doc:

https://github.com/augnustin/i18n-node-yaml#set-the-localelanguage

Please close if it works for you.

Best

**Comment by drackp2m** [comment]
Hi,

It still does not work. I'm going crazy to add a translation in my project.

I think I'll be doing something wrong in my application. Thanks for updating the documentation.

I close the issue, because whatever the case, the setLocale method is not accessible, but there are very valid alternatives.

Thank you very much.

**Comment by drackp2m** [comment]
Hi,

It still does not work. I'm going crazy to add a translation in my project.

I think I'll be doing something wrong in my application. Thanks for updating the documentation.

I close the issue, because whatever the case, the setLocale method is not accessible, but there are very valid alternatives.

Thank you very much.

**Comment by augnustin** [comment]
You can write me there if you'd like some assistance: https://augustin-riedinger.fr/en/contact/

**Comment by drackp2m** [comment]
Thanks, I hope I do not have to do it, however, thanks for the offer and, nice web.
:D
